name: Run gtests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: sh build.sh && rm -rf build

    - name: Build project again with coverage
      run: sh build_with_coverage.sh

    - name: Run gtests
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ./build/advanced-datastructures-st22/tests/ads_test -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: test-results/**/*.xml

    - name: Extract coverage
      run: sh extract_coverage.sh
